### ISSUE TITLE
transact to VRFConsumer.rawFulfillRandomWords errored: Error encoding arguments: Error: expected array value (argument=null, value="10", code=INVALID_ARGUMENT, version=abi/5.5.0)

### ISSUE THREAD

**Issue by junjiequ123** [realran/VRFContract#14]
steps
1. skip details of compile & deploy 
2. contract address in dev net is : 0x7e87d6b3514Db708dfA2e0bCB10C0d818349ea9A
3. call rawfulfillRandomWords on REMIX

Found this version requires two inputs 
1. requestID
2. randomWords

according to https://docs.realran.com/Docs/Getting%20Started/Get%20a%20Random%20Number
it only requires the second parameter....then, got error

transact to VRFConsumer.rawFulfillRandomWords errored: Error encoding arguments: Error: expected array value (argument=null, value="10", code=INVALID_ARGUMENT, version=abi/5.5.0)

**Comment by oiioio2022** [comment]
The documentation in this place is wrong, the syncRequestRandomWords method of the consumer contract should be called.

**Comment by junjiequ123** [comment]
the document has conflicts between words and screen copies.... 

by call syncRequestRandomWords, it works.

I am looking for a simple lucky draw use case demo of this ;) please let me know where I could find one.
